/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BanquetRouteImport } from './routes/banquet'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHotelsRouteImport } from './routes/admin/hotels'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminHotelsIdRouteImport } from './routes/admin/hotels.$id'

const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BanquetRoute = BanquetRouteImport.update({
  id: '/banquet',
  path: '/banquet',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHotelsRoute = AdminHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHotelsIdRoute = AdminHotelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminHotelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/banquet': typeof BanquetRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/rooms': typeof RoomsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/hotels': typeof AdminHotelsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/hotels/$id': typeof AdminHotelsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banquet': typeof BanquetRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/rooms': typeof RoomsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/hotels': typeof AdminHotelsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/hotels/$id': typeof AdminHotelsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/banquet': typeof BanquetRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/rooms': typeof RoomsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/hotels': typeof AdminHotelsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/hotels/$id': typeof AdminHotelsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/banquet'
    | '/contact'
    | '/gallery'
    | '/rooms'
    | '/admin/customers'
    | '/admin/feedback'
    | '/admin/hotels'
    | '/admin/login'
    | '/admin/'
    | '/admin/hotels/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/banquet'
    | '/contact'
    | '/gallery'
    | '/rooms'
    | '/admin/customers'
    | '/admin/feedback'
    | '/admin/hotels'
    | '/admin/login'
    | '/admin'
    | '/admin/hotels/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/banquet'
    | '/contact'
    | '/gallery'
    | '/rooms'
    | '/admin/customers'
    | '/admin/feedback'
    | '/admin/hotels'
    | '/admin/login'
    | '/admin/'
    | '/admin/hotels/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BanquetRoute: typeof BanquetRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  RoomsRoute: typeof RoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banquet': {
      id: '/banquet'
      path: '/banquet'
      fullPath: '/banquet'
      preLoaderRoute: typeof BanquetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hotels': {
      id: '/admin/hotels'
      path: '/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminHotelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hotels/$id': {
      id: '/admin/hotels/$id'
      path: '/$id'
      fullPath: '/admin/hotels/$id'
      preLoaderRoute: typeof AdminHotelsIdRouteImport
      parentRoute: typeof AdminHotelsRoute
    }
  }
}

interface AdminHotelsRouteChildren {
  AdminHotelsIdRoute: typeof AdminHotelsIdRoute
}

const AdminHotelsRouteChildren: AdminHotelsRouteChildren = {
  AdminHotelsIdRoute: AdminHotelsIdRoute,
}

const AdminHotelsRouteWithChildren = AdminHotelsRoute._addFileChildren(
  AdminHotelsRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminHotelsRoute: typeof AdminHotelsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminHotelsRoute: AdminHotelsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BanquetRoute: BanquetRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  RoomsRoute: RoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
